### ISSUE TITLE
Fedora CoreOS cannot be used as a source image

### ISSUE THREAD

**Issue by tesinormed** [hashicorp/packer-plugin-googlecompute#191]
## Overview

Using `fedora-coreos-stable` or any Fedora CoreOS as a source image will error out as it cannot find a image in the baked in image projects.

## Reproduction

See below for buildfile.

## Plugin and Packer version

Plugin version 1.1.2, Packer version 1.9.4

## Buildfile

```hcl
source "googlecompute" "<< NAME >>" {
    ...
    source_image_family = "fedora-coreos-stable"
    ...
}
```

### Operating system and Environment details

Fedora Silverblue, x86_64, [inside a toolbox](https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/)

**Comment by lbajolet-hashicorp** [comment]
Hi @tesinormed,

Thanks for bringing this up. I can indeed replicate this locally, and the reason why that happens is because the image you're looking for is from the `fedora-coreos-cloud` project, which is not in the list the plugin supports by default.

I'll open a PR to add it to the list, but seeing how it is implemented in the plugin hints that we should probably do things differently.
